# Generated by Django 5.0.3 on 2024-04-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='school_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams', to='app.schoolgroup'),
        ),
    ]
