# Generated by Django 5.0.3 on 2024-04-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_exam_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleLessons',
            new_name='Lessons',
        ),
    ]
