# Generated by Django 5.0.3 on 2024-04-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_schedulelessons_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='app.subject'),
        ),
    ]
