# Generated by Django 5.0.3 on 2024-04-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_grades_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.teacher'),
        ),
        migrations.CreateModel(
            name='ScheduleExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('school_group', models.ManyToManyField(to='app.schoolgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject')),
                ('teacher', models.ManyToManyField(related_name='subject_teachers', to='app.teacher')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
    ]
