# Generated by Django 5.0.3 on 2024-04-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lessons_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ManyToManyField(related_name='homeworks', to='app.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='homeworks', to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='app.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='app.parent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='app.teacher'),
        ),
    ]
