# Generated by Django 5.0.3 on 2024-04-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_grades_subject_alter_grades_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexams',
            name='school_group',
            field=models.ManyToManyField(blank=True, null=True, to='app.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='scheduleexams',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject'),
        ),
        migrations.AlterField(
            model_name='scheduleexams',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject_teachers', to='app.teacher'),
        ),
    ]
