# Generated by Django 5.0.3 on 2024-04-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_homework_group_alter_homework_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.schoolgroup'),
        ),
    ]
