# Generated by Django 5.0.3 on 2024-04-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_school_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='school_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='app.schoolgroup'),
        ),
    ]
