# Generated by Django 5.0.3 on 2024-04-01 20:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_scheduleexams_school_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexams',
            name='school_group',
            field=models.ManyToManyField(to='app.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_creation', models.DateField(default=datetime.datetime(2024, 4, 1, 20, 26, 43, 454952))),
                ('date_deadline', models.DateField(default=None)),
                ('group', models.ManyToManyField(to='app.schoolgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.teacher')),
            ],
        ),
    ]
