# Generated by Django 5.0.3 on 2024-04-02 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_photo_alter_homework_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 20, 36, 33, 590127)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
