# Generated by Django 5.0.3 on 2024-04-02 21:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_homework_date_creation_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 21, 49, 34, 45327)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/z '),
        ),
        migrations.CreateModel(
            name='ScheduleLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.schoolgroup')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject')),
                ('teacher', models.ManyToManyField(to='app.teacher')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
    ]
