# Generated by Django 5.0.3 on 2024-04-05 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_homework_date_creation_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 21, 33, 38, 890070)),
        ),
        migrations.AlterField(
            model_name='homework',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 21, 33, 38, 888671)),
        ),
    ]
